TRUNCATE TABLE public."Invoices" RESTART IDENTITY CASCADE;

TRUNCATE TABLE public."Orders" RESTART IDENTITY CASCADE;

TRUNCATE TABLE public."ReservationRooms" RESTART IDENTITY CASCADE;

TRUNCATE TABLE public."Bookings" RESTART IDENTITY CASCADE;

TRUNCATE TABLE public."Guests" RESTART IDENTITY CASCADE;